<?php

/**
 * @file
 * Contains testable.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function testable_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the testable module.
    case 'help.page.testable':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
