sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - env: SCRIPT='modules/relaxed/tests/bin/php-replicator.sh'
  fast_finish: true

services:
  - mysql
  - couchdb

addons:
  apt:
    packages:
    - nginx

env:
  matrix:
    - SCRIPT='modules/relaxed/tests/bin/drupal.sh'
    - SCRIPT='modules/relaxed/tests/bin/php-replicator.sh'
    - SCRIPT='modules/relaxed/tests/bin/drupal-to-couchdb.sh'
    - SCRIPT='modules/relaxed/tests/bin/couchdb-to-drupal.sh'
    - SCRIPT='modules/relaxed/tests/bin/drupal-to-drupal.sh'
    - SCRIPT='modules/relaxed/tests/bin/pouchdb.sh'

notifications:
  slack: det:YiOiwfzUBtt9aTnWvocK8uDI

cache:
  directories:
  - $HOME/.drush/cache/download

before_install:
  - mysql -uroot < $TRAVIS_BUILD_DIR/.travis/mysql.sql
  - cp $TRAVIS_BUILD_DIR/.travis/php.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/
  - cp $TRAVIS_BUILD_DIR/.travis/php-fpm.conf ~/.phpenv/versions/$(phpenv version-name)/etc/
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - nginx -c $TRAVIS_BUILD_DIR/.travis/nginx.conf
  - wget -P ~/ https://github.com/drush-ops/drush/releases/download/8.0.0-rc3/drush.phar && chmod +x ~/drush.phar
  - php ~/drush.phar make $TRAVIS_BUILD_DIR/.travis/drupal.make.yml $HOME/www
  - php ~/drush.phar --root=$HOME/www --yes site-install --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal0 testing

install:
  - ln -s $TRAVIS_BUILD_DIR ~/www/modules/relaxed

script:
  - cd ~/www && bash $SCRIPT
