api: 2

core: 8.x

projects:
  drupal: 8.1.x
  key_value: 1.x
  multiversion:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: https://github.com/dickolsson/drupal-multiversion.git
  relaxed:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: https://github.com/relaxedws/drupal-relaxed.git
