<?php

/**
* @file
* Contains Drupal\advisory_committee.module
*/

/**
 * @defgroup advisory_committee Advisory Committee: Create Content Type
 * @ingroup AdvisoryCommittee
 * @{
 * Impelement content entity for advisory committee.
 * }
 */ 
/**
* Implements HOOK_theme
**/
function advisory__committee_theme() {
	$theme['advisory_calendar'] = array(
		'variables' => array('main'=>NULL,'leftnav'=>NULL,'months_organized'=>NULL),
		'template' => 'advisory_calendar'
	);
	$theme['advisory_content'] = array(
                'variables' => array('main'=>NULL,'leftnav'=>NULL,'doctitle'=>NULL,'resources_for_you'=>''),
                'template' => 'advisory_content'
        );

	return $theme;
}

/**
* Implements HOOK_preprocess
**/
function advisory__committee_preprocess(&$variables, $hook){
		
}

/**
* Implements HOOK_theme_suggestions_page_alter
**/
function advisory__committee_theme_suggestions_page_alter(&$suggestions, $variables) {
	/*
	$node = \Drupal::request()->attributes->get('node');
	if($node && 'advisory_committee_content' == $node->getType()) {
		//$suggestions[] = 'advisory_content';
	}
	*/
}
